/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SudokuRow.java
 *
 * Created on 8 Aug, 2010, 5:05:37 PM
 */

package sudoku;

import java.awt.Dimension;
import java.awt.FlowLayout;
import javax.swing.JTextField;

/**
 *
 * @author Shivanth
 */
public class SudokuRow extends javax.swing.JPanel {

    /** Creates new form SudokuRow */
    public SudokuRow() {
        initComponents();
        tb= new JTextField[9];
        for(int i=0;i<9;i++){
            tb[i]=new JTextField();
            tb[i].setPreferredSize(new Dimension(20,20));
            add(tb[i]);
        }
        this.setLayout(new FlowLayout());
    }
    public SudokuRow(int [] a){
        initComponents();
        tb= new JTextField[9];
        for(int i=1;i<10;i++){
            tb[i-1]=new JTextField(Integer.toString(a[i]));
            tb[i-1].setPreferredSize(new Dimension(20,20));
            this.add(tb[i-1]);
        }
        this.setLayout(new FlowLayout());
    }

    public int getBoxValue(int i){
        try{
            if(tb[i].getText().equals(""))
                return 0;
            else
        return Integer.parseInt(tb[i].getText());
        }
        catch(Exception e){
            return -1;
        }

    }
    public JTextField getBox(int i){
        return this.tb[i];
    }
    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    //@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
        JTextField tb[];

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
